### ISSUE TITLE
extractJson() should throw error for invalid input

### ISSUE THREAD

**Issue by anistark** [iotaledger/iota.lib.js#230]
### Bug description
My `iota.utils.extractJson(bundle)` returns `Promise { <pending> }` even after waiting long time. 

### Hardware Spec
On what hardware is the node running on?
Local system. Mac Darwin Kernel Version 16.7.0

### Steps To Reproduce
1. Using iota.lib.js v0.4.7, passed bundle array to extractJson function
2. Returned `Promise { <pending> }` even after waiting a long time.

### Expected behaviour
- It should return the JSON encoded message for valid bundle with valid encoded *ASCII*  JSON.
- It should return empty JSON message (`{}`) for all signature fragments being all 9s.
- It should throw `Invalid input` error for non-bundle input.
- It should throw `Invalid bundle` error for invalid bundle.
- It should throw `Invalid non-ASCII message` error for JSON with chars outside ASCII charset. 
- It should throw `Invalid JSON encoded message` error in all other cases.

### Actual behavior
- `null` was returned for invalid input
- `Promise` was returned for input of promise type

**Comment by heavyengineer** [comment]
Can you not resolve the promise?

**Comment by chrisdukakis** [comment]
Hi, could you try: `p.then(bundle => iota.utils.extractJson(bundle))`? I think it should solve the issue.

**Comment by anistark** [comment]
I did try that. Did not resolve the issue. Finally, figured out the issue.. The trytes conversion weren't ascii characters all of them. Something must have went wrong with the toTrytes function or problem with max size of signatureMessageFragment.
Beyond the scope of this library it seems.

I'll figure out an alternate way around.

**Comment by chrisdukakis** [comment]
@anistark I edited "Expected behaviour" section of your description, please feel free to review!

**Comment by anistark** [comment]
@chrisdukakis Looks good ! But if the encoded message isn't ASCII, it seems it doesn't throw any error. Just returns `null` or if passed with promise, returns `pending`.

Maybe, this can be a sort of enhancement to be updated.

**Comment by chrisdukakis** [comment]
Thank you, good catch about non-ascii chars! It's enhancement, yes and a bug fix. Returning `null` isn't a valid expected behaviour for sure.

**Comment by chrisdukakis** [comment]
Closing, issue is fixed in [`@iota/extract-json`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/extract-json)
